 
name: Kodi-Addon-Check

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Kodi-Addon-Check
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kodi-addon-checker
      - name: Check LEIA
        run: kodi-addon-checker --branch leia

  deploy:
    name: Deploy Addon
    needs: test
    runs-on: ubuntu-latest

    steps:
     - name: Send Repository Dispatch
       uses: peter-evans/repository-dispatch@v1
       with:
         token: ${{ secrets.PAT_TOKEN }}
         repository: Space2Walker/kodi-space-repo
         event-type: Leia
